import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "../app/Components/app-sidebar"; // Importing AppSidebar


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Royal 9 Engine Oil",
  description: "Designed and Generated By Subham Dubey",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          {/* Render AppSidebar for the sidebar content */}
          <AppSidebar />
          
          {/* Main content area */}
          <main>
            {/* SidebarTrigger can be placed here or elsewhere */}
            <SidebarTrigger />
          
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
