import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "../app/Components/app-sidebar"; // Importing AppSidebar

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SidebarProvider>
          {/* Render AppSidebar for the sidebar content */}
          <AppSidebar />
          
          {/* Main content area */}
          <main>
            {/* SidebarTrigger can be placed here or elsewhere */}
            <SidebarTrigger />
          
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
